### ISSUE TITLE
Flycheck integration

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#6]
@pwalsh First of all, thank you for plugin.

It would be convenient to set `flycheck` python executables automatically (or update PATH for it) to avoid setup it like `pipenv run flake8` (which fragile, because depend on current CMD). 

Also consider possibility for better `projectile` integration.

**Comment by Pitometsu** [comment]
Wouldn't it be good to use https://github.com/proofit404/pythonic/blob/master/pythonic.el as a dependency to manage virtualenvs?

**Comment by pwalsh** [comment]
Hi @Pitometsu thanks for your interest! This is still very much a work in progress, but I think I'll have something generally useful in the next 2 weeks. I'm also very happy for contributions.

For specific discussion on the points you raise, integrations are in #5 and I now opened #7 for consideration of Pythonic as a dependency of Pipenv. Because these issues are more focussed, I'll close this one and we can discuss there?
